name: Build the game

on:
  push:
    branches: [master-dev]
  workflow_dispatch:
jobs:
  
  BuildMobileCache:
    name: Build Caches
    permissions: write-all
    uses: ./.github/workflows/dependencies.yml
    with:
      os: macos-15
      CACHE_NAME: P-Slice.1.0.mobile-cache2
      setupScript: sh ./setup/mobile.sh
  BuildDesktopCache:
    name: Build Caches
    permissions: write-all
    uses: ./.github/workflows/dependencies.yml
    with:
      os: ubuntu-24.04
      setupScript: sh ./setup/unix.sh
      CACHE_NAME: P-Slice.1.0.desktop-cache2
  BuildDesktop:
    name: Build Desktop
    needs: BuildDesktopCache
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: "windows -final"
            exportPath: windows
            artifactName: P-Slice.1.0.windows
            cacheLibrariesPath: P-Slice.1.0.desktop-cache2
            cachePath: P-Slice.1.0.build-windows2
            artifactPath: export\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: "linux -final"
            exportPath: linux
            artifactName: P-Slice.1.0.linux
            cachePath: P-Slice.1.0.build-linux2
            cacheLibrariesPath: P-Slice.1.0.desktop-cache2
            artifactPath: export/release/linux/bin/*

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}

  BuildMobile:
    permissions: write-all
    needs: BuildMobileCache
    name: Build mobile
    strategy:
      matrix:
        include:
          - name: Android
            os: ubuntu-24.04
            exportPath: android
            buildArgs: "android"
            cacheLibrariesPath: P-Slice.1.0.mobile-cache2
            artifactName: P-Slice.1.0.android
            cachePath: P-Slice.1.0.build-android2
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}
